import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { SITE } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Bot Terms & Privacy — ${SITE.name}`,
  description: "Terms of service and privacy policy for the Discord bots operated by the Kova project.",
  alternates: { canonical: "/bot-terms" },
};

const effectiveDate = "September 1, 2026";

export default function BotTermsPage() {
  return (
    <>
      <Header />
      <div className="rail">
        <section style={{ borderTop: "none" }}>
          <Link
            href="/"
            className="text-xs font-medium"
            style={{ color: "var(--oc-text-muted)", fontFamily: "var(--oc-font-mono)" }}
          >
            ← Back to home
          </Link>
          <p className="oc-eyebrow" style={{ marginTop: "20px" }}>
            Kova Discord Bots
          </p>
          <h1
            className="hero-title"
            style={{
              marginTop: "12px",
              marginBottom: "16px",
              fontFamily: "var(--oc-font-serif)",
            }}
          >
            Bot Terms & <em>Privacy</em>
          </h1>
          <p className="hero-desc">
            The Discord bots operated by the Kova project read messages in channels they are
            invited to, send that text to AI model providers to produce a reply, and store the
            conversation on servers we control. We do not sell your data and we do not show ads.
          </p>
          <p
            className="text-sm"
            style={{ color: "var(--oc-text-muted)", marginTop: "16px" }}
          >
            Effective {effectiveDate}
          </p>
        </section>

        <section
          id="terms"
          className="rounded-xl p-6 md:p-8"
          style={{
            border: "1px solid var(--oc-border-subtle)",
            background: "var(--oc-surface-card)",
          }}
        >
          <h2
            style={{
              fontFamily: "var(--oc-font-serif)",
              fontSize: "1.5rem",
              fontWeight: 600,
              color: "var(--oc-text-primary)",
              marginBottom: "20px",
            }}
          >
            Terms of Service
          </h2>

          <BotSection title="Who we are and what this covers">
            <p>
              These terms cover the Discord applications operated by the Kova project, including
              any official Kova-branded bot. The bots are built on the open-source Kova project
              and are run by the project maintainers. By using a bot, or by participating in a
              channel where one is present, you agree to these terms.
            </p>
          </BotSection>

          <BotSection title="What the service does">
            <p>
              Each bot is an AI assistant. It reads messages addressed to it, and in some channels
              the surrounding conversation, and replies using third-party AI models. Replies are
              generated by software and may be wrong, incomplete, or out of date. Do not rely on a
              bot for legal, financial, medical, or safety-critical decisions, and verify anything
              that matters.
            </p>
          </BotSection>

          <BotSection title="Acceptable use">
            <p>You agree not to use a bot to:</p>
            <ul>
              <li>break Discord&apos;s Terms of Service or Community Guidelines, or any applicable law;</li>
              <li>harass, threaten, defame, or impersonate anyone;</li>
              <li>generate or distribute malware, spam, or content that sexualises minors;</li>
              <li>attempt to extract credentials, secrets, or other users&apos; private data; or</li>
              <li>deliberately disrupt the service, for example by automated flooding.</li>
            </ul>
            <p>
              We may rate-limit, ignore, remove, or block any user, channel, or server at our
              discretion, with or without notice.
            </p>
          </BotSection>

          <BotSection title="Availability and changes">
            <p>
              The bots are provided free of charge, as-is and as-available, with no warranty of any
              kind. We may change, suspend, or discontinue any bot at any time, and we do not
              guarantee uptime, response quality, or retention of any conversation. To the fullest
              extent permitted by law, the Kova project and its maintainers are not liable for any
              damages arising from use of the bots.
            </p>
          </BotSection>

          <BotSection title="Your content">
            <p>
              You keep any rights you have in what you write. You grant us permission to process
              your messages as described in the Privacy Policy below, for the purpose of operating
              the service.
            </p>
          </BotSection>

          <BotSection title="Changes to these terms">
            <p>
              We may update these terms. The effective date above changes when we do. Continued
              use after an update means you accept the revised terms.
            </p>
          </BotSection>
        </section>

        <section
          id="privacy"
          className="rounded-xl p-6 md:p-8"
          style={{
            border: "1px solid var(--oc-border-subtle)",
            background: "var(--oc-surface-card)",
          }}
        >
          <h2
            style={{
              fontFamily: "var(--oc-font-serif)",
              fontSize: "1.5rem",
              fontWeight: 600,
              color: "var(--oc-text-primary)",
              marginBottom: "20px",
            }}
          >
            Privacy Policy
          </h2>

          <BotSection title="What we process">
            <ul>
              <li>
                <strong>Message content</strong> in channels and threads where a bot is present
                and permitted to read, and in direct messages you send to a bot. In most channels a
                bot only receives messages that mention it; where a server operator has enabled
                it, a bot may receive other messages in that channel as context.
              </li>
              <li>
                <strong>Identifiers and metadata</strong>: Discord user, channel, server, and
                message IDs, display names, timestamps, and the roles relevant to access control.
              </li>
              <li>
                <strong>Attachments and links</strong> you send to a bot, when the bot needs them
                to answer.
              </li>
            </ul>
            <p>We do not request or store your Discord password, email, or payment details.</p>
          </BotSection>

          <BotSection title="Why we process it">
            <p>
              To generate replies, to maintain conversation context, to operate access controls
              and abuse protection, and to diagnose faults. We do not use your messages to train
              our own models, we do not sell or rent your data, and we do not run advertising or
              third-party analytics inside the bots.
            </p>
          </BotSection>

          <BotSection title="Who else sees it">
            <p>
              To produce a reply, message text and relevant context are sent to third-party AI
              model providers, which currently include OpenAI and Anthropic. Their handling is
              governed by their own terms and privacy policies. Server operators and maintainers
              with administrative access to the machine running a bot can read stored
              conversations for that bot.
            </p>
          </BotSection>

          <BotSection title="Where it is stored">
            <p>
              Conversations are stored on servers controlled by the project maintainers,
              currently hosted with Hetzner in the United States and Germany, and on
              maintainer-operated machines. There is no central Kova cloud that aggregates bot
              conversations across unrelated servers.
            </p>
          </BotSection>

          <BotSection title="How long we keep it">
            <p>
              Conversation history is retained so a bot can maintain context, and is kept until it
              is no longer needed for operating the service or until deletion is requested.
              Diagnostic logs are kept for a shorter period. We may retain records where we are
              legally required to.
            </p>
          </BotSection>

          <BotSection title="Your choices">
            <p>
              You can stop sharing data with a bot by not addressing it and by leaving or muting
              channels where it is present. You may request access to, correction of, or deletion
              of the data we hold about you, and depending on where you live you may have
              additional rights under laws such as the GDPR. Requests that would require deleting
              other people&apos;s messages, or that conflict with a legal obligation, may be limited
              in scope.
            </p>
          </BotSection>

          <BotSection title="Children">
            <p>
              The bots are not directed at children. You must meet Discord&apos;s minimum age
              requirement for your country to use them.
            </p>
          </BotSection>

          <BotSection title="Contact">
            <p>
              For privacy requests, security reports, or questions about these terms, contact{" "}
              <a
                href="mailto:chiragborse877@gmail.com"
                style={{ color: "var(--oc-accent-primary)" }}
              >
                chiragborse877@gmail.com
              </a>
              , or open an issue at{" "}
              <a
                href="https://github.com/OpenKova/kova"
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "var(--oc-accent-primary)" }}
              >
                github.com/OpenKova/kova
              </a>
              .
            </p>
          </BotSection>
        </section>
      </div>
      <Footer />
    </>
  );
}

function BotSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginTop: "24px" }}>
      <h3
        style={{
          fontSize: "1.05rem",
          fontWeight: 600,
          color: "var(--oc-text-primary)",
          marginBottom: "10px",
        }}
      >
        {title}
      </h3>
      <div
        style={{
          color: "var(--oc-text-secondary)",
          fontSize: "0.98rem",
          lineHeight: 1.7,
        }}
      >
        {children}
      </div>
    </section>
  );
}
